name: Gestion de contenu d'un site php, utilisant Mysql DB sur Docker et Ubuntu

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout du repository
    - name: Checkout du repository
      uses: actions/checkout@v2
      
    # Setup du PHP, des extensions et de Composer
    - name: Setup du PHP, des extensions et de Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo
      env:
        update: true
          
    # Installation des dépendeces de Composer
    - name: Installation des dépendeces de Composer
      working-directory: ./marketlev
      run: composer install

    # Build et run du Docker containers
    - name: Build et run du Docker containers
      working-directory: ./marketlev
      run: |
        docker-compose up --build -d

    # Debugging steps
    - name: Debug GitHub Token
      run: echo ${{ secrets.GITHUB_TOKEN }}

    - name: Debug Repository URL
      run: echo "https://github.com/mimip13/workflow.git"
      
    # Deployement
    - name: Deployement
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
