name: Gestion de contenu d'un site php, utilisant Mysql DB sur Docker et Ubuntu

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v2
      
    # Setup PHP, extensions, and Composer
    - name: Setup PHP, extensions, and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo
      env:
        update: true
          
    # Install Composer dependencies
    - name: Composer Install
      working-directory: ./marketlev
      run: composer install

    # Build and run Docker containers
    - name: Build and run Docker containers
      working-directory: ./marketlev
      run: |
        docker-compose up --build -d

    # Deploy (if needed)
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
