name: Gestion de contenu d'un site php, utilisant Mysql DB sur Docker et Ubuntu

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout du repository
    - name: Checkout du repository
      uses: actions/checkout@v2
      
    # Setup du PHP, des extensions et de Composer
    - name: Setup du PHP, des extensions et de Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo
      env:
        update: true
          
    # Installation des dépendances de Composer
    - name: Installation des dépendances de Composer
      run: composer install
      working-directory: ./marketlev

    # Build et run du Docker containers
    - name: Build et run du Docker containers
      run: |
        docker-compose up --build -d
      working-directory: ./marketlev

    # Déploiement
    - name: Déploiement
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.PATH}}
        publish_dir: ./output
